# Generated by Django 5.0.7 on 2024-07-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxAllApp', '0003_producto_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
