# Generated by Django 5.0.7 on 2024-07-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=32),
        ),
    ]
